### ISSUE TITLE
Can't compile example "Failed to construct terminal; falling back to unsupported"

### ISSUE THREAD

**Issue by fancywriter** [heroku/scala-getting-started#5]
Basically it doesn't work when I am trying to run `sbt`. :-(
```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
        at jline.UnixTerminal.<init>(UnixTerminal.java:64)
        at jline.UnixTerminal.<init>(UnixTerminal.java:49)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
        at jline.TerminalFactory.create(TerminalFactory.java:100)
        at jline.TerminalFactory.get(TerminalFactory.java:184)
        at jline.TerminalFactory.get(TerminalFactory.java:190)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:240)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:232)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:220)
        at sbt.JLine$$anonfun$createReader$1.apply(LineReader.scala:100)
        at sbt.JLine$$anonfun$createReader$1.apply(LineReader.scala:99)
        at sbt.JLine$$anonfun$usingTerminal$1.apply(LineReader.scala:95)
        at sbt.JLine$$anonfun$usingTerminal$1.apply(LineReader.scala:93)
        at sbt.JLine$.withTerminal(LineReader.scala:86)
        at sbt.JLine$.usingTerminal(LineReader.scala:93)
        at sbt.JLine$.createReader(LineReader.scala:99)
        at sbt.FullReader.<init>(LineReader.scala:129)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:173)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:170)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:54)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by kudryashovaia** [comment]
have you solve this problem? I have the same issue(

**Comment by fancywriter** [comment]
@kudryashovaia this project looks abandoned. Last commit in 2016.

You could try to resurrect it, I would start from updating SBT to recent version. But I doubt that changes will be accepted. Please check this branch #6, it could work.

**Comment by Malax** [comment]
This should be fixed with the recent update I made to the app which also brings it up to date for modern Scala, sbt and Play. Feel free to open another issue or re-open this one should it still be relevant. Thanks!
